### ISSUE TITLE
Mouse events don't work in noVNC on touchscreens

### ISSUE THREAD

**Issue by jankeromnes** [jankeromnes/janitor#11]
On both a Dell XPS 13 and a Chromebook Pixel, noVNC doesn't seem to propage mouse events (click, right click, drag) whereas keyboard strokes work fine. On a Thinkpad W540, both mouse and keyboard events work fine.

I suspect the touchscreens in both the Dell and the Chromebook. See also https://github.com/kanaka/noVNC/issues/510.

**Comment by jankeromnes** [comment]
It looks like https://github.com/kanaka/noVNC/pull/369 could fix this.

**Comment by jankeromnes** [comment]
Workaround: Disable touch, either in the browser or at OS-level.

**Comment by patrakov** [comment]
The fix recently entered noVNC master, please test

**Comment by jankeromnes** [comment]
@patrakov Indeed, thanks for the update! I confirm that this bug is fixed in newer versions of noVNC. It should stop happening on Janitor images that are less than 1 month old (nightly image updates are disabled due to temporary resource shortage).
