### ISSUE TITLE
EDITOR env var unset in new terminal tabs

### ISSUE THREAD

**Issue by freaktechnik** [jankeromnes/janitor#18]
When closing the original terminal tab and opening a new one, some functions (like doing an interactive rebase) will not work anymore, because git cannot find an editor. This is due to the `EDITOR` environment variable being unset.

**Comment by jankeromnes** [comment]
Thanks for reporting this problem! It should now be fixed in recent project images, because https://github.com/jankeromnes/dockerfiles/commit/c37591cacc6db8e199c5af23c0d8dfd4653c62ae sets `EDITOR=vim` in `/home/user/.bashrc`.
