### ISSUE TITLE
Cannot run Servo

### ISSUE THREAD

**Issue by Coder206** [jankeromnes/janitor#21]
I was unsuccessful in running Servo on the VNC and in Cloud9. Please note, I tried downloading the packages from the Servo page.

Here are the errors:

error: XDG_RUNTIME_DIR not set in the environment.
thread 'main' panicked at 'Failed to create window.: NoBackendAvailable(XOpenDisplayFailed)', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x7f981b63eaaf - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x7f981b6466db - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x7f981b64633f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x7f981a7f196a - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h1b136c5b997dba9d
                        at /home/user/servo/components/util/panicking.rs:45
   5:     0x7f981a7f1829 - _<std..thread..local..LocalKey<T>>::with::h813eaa2cabd28878
                        at ../src/libstd/thread/local.rs:211
   6:     0x7f981a7f16a6 - util::panicking::initiate_panic_hook::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::he9b75ed68d2396bf
                        at /home/user/servo/components/util/panicking.rs:40
   7:     0x7f981b62c3cc - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   8:     0x7f981b646921 - std::panicking::begin_panic::he426e15a3766089a
   9:     0x7f981b62dc3a - std::panicking::begin_panic_fmt::hdddb415186c241e7
  10:     0x7f981b6468be - rust_begin_unwind
  11:     0x7f981b67cebf - core::panicking::panic_fmt::hf4e16cb7f0d41a25
  12:     0x7f981756bef1 - core::result::unwrap_failed::he361ed66efb41daa
                        at ../src/libcore/macros.rs:29
  13:     0x7f9817568671 - _<core..result..Result<T, E>>::expect::h916c1c9ac8d3ac38
                        at ../src/libcore/result.rs:747
  14:     0x7f98175650b0 - glutin_app::window::Window::new::h20f7c31a0a63b85b
                        at /home/user/servo/ports/glutin/window.rs:162
  15:     0x7f9817564680 - glutin_app::create_window::hb54113b9ee251b02
                        at /home/user/servo/ports/glutin/lib.rs:48
  16:     0x7f98174219fe - servo::main::h6924e5658370f6b5
                        at /home/user/servo/components/servo/main.rs:105
  17:     0x7f981b645cb8 - std::panicking::try::call::h852b0d5f2eec25e4
  18:     0x7f981b650b1b - __rust_try
  19:     0x7f981b650abe - __rust_maybe_catch_panic
  20:     0x7f981b64575e - std::rt::lang_start::hfe4efe1fc39e4a30
  21:     0x7f98175505a9 - main
  22:     0x7f98146ce82f - __libc_start_main
  23:     0x7f981741f968 - _start
  24:                0x0 - <unknown>
Servo exited with return value 101

**Comment by jankeromnes** [comment]
Hi @Coder206, thanks for reporting this bug!

It is not currently possible to run Servo from Cloud9 directly, because there is no graphical environment available there (X server).

It is possible however to run it over noVNC, but only with web render.

Could you please try running Servo with the following command in the VNC interface?

    ./mach run -d -w

-w is for webrender, and -d is for debug build (please use -r instead if you previously compiled with ./mach build -r).

**Comment by Coder206** [comment]
@jankeromnes That makes sense! I tried running with web render, it works. :) Thanks!

**Comment by jankeromnes** [comment]
That's great! Glad it now works for you :)
