### ISSUE TITLE
Could I get my Cloud9 premium account free?

### ISSUE THREAD

**Issue by notriddle** [jankeromnes/janitor#27]
Username on C9 is also notriddle.

**Comment by Coder206** [comment]
@notriddle Are you referring to the individual plan shown on the c9.io site?

**Comment by jankeromnes** [comment]
Hi @notriddle! Thanks a lot for your interest in the project :) I've just added you to the Janitor Team Account on c9.io, which gives you access to Cloud9 premium features and allows you to use the Janitor (unfortunately, that's still a manual process, but I try to be as quick as possible and the whole sign-up process will be much improved/automated soon!).

Welcome to the Janitor!
