### ISSUE TITLE
Can't push to GitHub with 2FA enabled

### ISSUE THREAD

**Issue by notriddle** [jankeromnes/janitor#28]
I'm working on Servo, so contributions are made using GitHub. Since Janitor doesn't link to GitHub in any way, running `git push` with the intent of creating a pull request asks for my GH username and password. Normally, this would work...

But I have two-factor authentication turned on. You can do it with a personal access token, but that is a gigantic pain.

Could we have the Janitor request a token itself with oAuth?

**Comment by jankeromnes** [comment]
Hi @notriddle, thanks for the feedback! Indeed the push-to-github experience isn't great yet, even if you don't have 2FA. I'm intending to implement a "Sign in with GitHub" option using oAuth, and this could ask GitHub for permission to add SSH keys, and then pre-authorize a user-specific SSH key to push from Janitor containers. I'll try to implement this as soon as possible, but it might take a few months before it's ready.

Another way for you to enable pushing is to generate an SSH key (or copy your `~/.ssh/id_rsa` and `~/.ssh/id_rsa.pub` from Cloud9 into your container, if you're not affraid of storing your Cloud9 keys on Janitor containers), authorize it on GitHub, and push to `git@github.com:user/repo` URLs. I know it's not much better than personal access tokens, so I'll try to get the oAuth link in soon.

**Comment by jankeromnes** [comment]
Marking this issue as fixed, since we [installed `hub`](https://github.com/jankeromnes/dockerfiles/commit/581c7a23bd09dac9831996e63da1424ab0f65540) for all images, and it supports pushing to GitHub with 2FA. @notriddle please re-open this issue if you feel there is more work to do here.
