### ISSUE TITLE
How works

### ISSUE THREAD

**Issue by Mte90** [jankeromnes/janitor#6]
If I want to use it locally there is a documentations?
I think as example for an event or hackaton.

**Comment by jankeromnes** [comment]
Short answer: You could use it locally, but in most cases it's better to use it online at https://janitor.technology

Longer answer:
- There is no documentation for this yet, but you can use it locally on Debian/Ubuntu (it's what I do for development).
- However, the Makefile is currently set up to install [Shipyard](http://shipyard-project.com/), which is not needed anymore. In the future I will remove the Shipyard steps and make Janitor use [Docker Swarm](https://docs.docker.com/swarm/).
- If you really want to use the Janitor locally now, and not wait for the new Makefile version, then on Ubuntu/Debian you could try running `make db https npm localengine`, and then `node app` should start a local Janitor on https://localhost:1443 (you can also use `sudo make ports` to set up an unprivileged link between ports 443 and 1443, then just use https://localhost).
