### ISSUE TITLE
WIthout c9.io is possible?

### ISSUE THREAD

**Issue by Mte90** [jankeromnes/janitor#7]
As I can see after the registration on c9.io is required a princing plan.
But I can see that is only a ssh connection so i think that is possible to use it without c9.io.

**Comment by jankeromnes** [comment]
To use the Janitor today with a great and full-featured IDE, you need a free [c9.io](https://c9.io) account (no need to pay anything, the Janitor can set up an SSH workspace on your free Cloud9 account).

You could also use Janitor without c9.io if you're not interested in having an IDE: All Janitor instances can be accessed via SSH, and instructions on how to log into your containers will soon be displayed in your user account.

**Comment by Mte90** [comment]
thank you far that information :-)
For the free account I get an error about workspace that I don't have.

**Comment by jankeromnes** [comment]
Thanks for the feedback! The Cloud9 link doesn't quite work yet, but it should soon (I'll send invite emails once it works).

Today, you might see something like "Can't login via SSH", which is expected (see issue #2). However, if the error you see is different, please share more details about it.

**Comment by EtienneWan** [comment]
It seems that cloud9 changed his free plan and moved ssh workspaces to paid plans (plus the fact free plan is limited to one private workspace)
I cannot create a ssh worskpace for a personal project with my free plan. You might need to discuss with the cloud9 team to know if your project can work with free plan accounts...

**Comment by jankeromnes** [comment]
Indeed, it looks like ssh workspaces became premium-only :/ thank you both again for checking.

I reached out to cloud9, and we found a solution that allows Janitor users to use SSH workspaces on c9.io, meaning the alpha version can still launch this month. Hooray!
